// board actions
export const FETCH_BOARDS = "FETCH_BOARDS";
export const FETCH_BOARDS_PENDING = "FETCH_BOARDS_PENDING";
export const FETCH_BOARDS_FULFILLED = "FETCH_BOARDS_FULFILLED";
export const FETCH_BOARDS_REJECTED = "FETCH_BOARDS_REJECTED";
