// board actions
export const GET_ALL_BOARDS = "GET_ALL_BOARDS";
export const GET_ALL_BOARDS_PENDING = "GET_ALL_BOARDS_PENDING";
export const GET_ALL_BOARDS_FULFILLED = "GET_ALL_BOARDS_FULFILLED";
export const GET_ALL_BOARDS_REJECTED = "GET_ALL_BOARDS_REJECTED";

export const GET_BOARD = "GET_BOARD";
export const GET_BOARD_PENDING = "GET_BOARD_PENDING";
export const GET_BOARD_FULFILLED = "GET_BOARD_FULFILLED";
export const GET_BOARD_REJECTED = "GET_BOARD_REJECTED";

// thread actions
export const GET_THREAD = "GET_THREAD";
export const GET_THREAD_PENDING = "GET_THREAD_PENDING";
export const GET_THREAD_FULFILLED = "GET_THREAD_FULFILLED";
export const GET_THREAD_REJECTED = "GET_THREAD_REJECTED";

export const CREATE_THREAD = "CREATE_THREAD";
export const CREATE_THREAD_PENDING = "CREATE_THREAD_PENDING";
export const CREATE_THREAD_FULFILLED = "CREATE_THREAD_FULFILLED";
export const CREATE_THREAD_REJECTED = "CREATE_THREAD_REJECTED";
